Repository Geoplateforme/plugin-qgis-geoplateforme, pull requests merged in 2025-06, with the labels that each got.

#97 feat(raster tiles): add wizard for raster tiles creation from WMS-VECTOR service
  geoplateforme/api/configuration.py
  geoplateforme/api/datastore.py
  geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_edition.py
  geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_edition.ui
  geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_status.py
  geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_status.ui
  geoplateforme/gui/create_raster_tiles_from_wms_vector/wzd_raster_tiles_from_wms_vector.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_service_details.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py
Labels: enhancement, UI/UX

#98 feat(wms raster): init processing for publication
  docs/usage/processings.md
  geoplateforme/processing/provider.py
  geoplateforme/processing/wms_raster_publication.py
  geoplateforme/resources/help/wms_raster_publish.md
Labels: documentation, enhancement

#100 feat(wmts): init processing for publication
  docs/usage/processings.md
  geoplateforme/processing/provider.py
  geoplateforme/processing/wmts_publication.py
  geoplateforme/resources/help/wmts_publish.md
Labels: documentation, enhancement

#101 feat(wmts): add wizard for publication
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/wmts_publication/qwp_publication_form.py
  geoplateforme/gui/wmts_publication/qwp_publication_form.ui
  geoplateforme/gui/wmts_publication/qwp_wmts_edition.py
  geoplateforme/gui/wmts_publication/qwp_wmts_edition.ui
  geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
  geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.ui
  geoplateforme/gui/wmts_publication/wzd_publication_creation.py
Labels: enhancement, UI/UX

#103 feat(procesing): move processing to a dedicated dir for each group
  geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_status.py
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
  geoplateforme/gui/update_publication/qwp_update_status.py
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/gui/upload_creation/wdg_layer_selection.py
  geoplateforme/gui/upload_creation/wdg_upload_creation.py
  geoplateforme/gui/upload_database_integration/qwp_upload_database_integration.py
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
  geoplateforme/gui/wms_raster_publication/qwp_wms_raster_publication_status.py
  geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
  geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
  geoplateforme/processing/generation/create_raster_tiles_from_wms_vector.py
  geoplateforme/processing/generation/tile_creation.py
  geoplateforme/processing/generation/upload_database_integration.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/publication/upload_publication.py
  geoplateforme/processing/publication/wfs_publication.py
  geoplateforme/processing/publication/wms_publication.py
  geoplateforme/processing/publication/wms_raster_publication.py
  geoplateforme/processing/publication/wmts_publication.py
  geoplateforme/processing/tools/check_layer.py
  geoplateforme/processing/tools/create_geoserver_style.py
  geoplateforme/processing/tools/sld11-10.xsl
  geoplateforme/processing/tools/sld_downgrade.py
  geoplateforme/processing/update_tile_upload.py
  geoplateforme/processing/upload/upload_from_files.py
  geoplateforme/processing/upload/upload_from_layers.py
  geoplateforme/processing/vector_db_creation.py
  tests/qgis/processings/test_check_layer.py
Labels: enhancement, quality, UI/UX

#106 Feature/add provider gpf
  geoplateforme/gui/provider/__init__.py
  geoplateforme/gui/provider/capabilities_reader.py
  geoplateforme/gui/provider/mdl_search_result.py
  geoplateforme/gui/provider/provider_dialog.py
  geoplateforme/gui/provider/provider_dialog.ui
  geoplateforme/gui/provider/provider_gpf.py
  geoplateforme/plugin_main.py
  geoplateforme/toolbelt/preferences.py
Labels: enhancement, UI/UX

#104 feat(delete): add processing to delete stored data and associated offering and configuration
  docs/usage/processings.md
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/storage/dlg_storage_report.py
  geoplateforme/processing/delete_data.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/tools/delete_stored_data.py
  geoplateforme/resources/help/delete_stored_data.md
Labels: documentation, enhancement, UI/UX

#105 feat(delete): add delete action for stored data
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
Labels: enhancement, UI/UX

#122 feat(user key): display available keys in table
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/user_key.py
  geoplateforme/gui/user_keys/dlg_user_keys.py
  geoplateforme/gui/user_keys/dlg_user_keys.ui
  geoplateforme/gui/user_keys/mdl_user_keys.py
  geoplateforme/gui/user_keys/wdg_user_keys.py
  geoplateforme/gui/user_keys/wdg_user_keys.ui
  geoplateforme/plugin_main.py
Labels: enhancement, UI/UX

#124 feat(permission): add widget to display permission in closed services
  geoplateforme/gui/dashboard/wdg_service_details.py
  geoplateforme/gui/dashboard/wdg_service_details.ui
  geoplateforme/gui/permissions/mdl_permissions.py
  geoplateforme/gui/permissions/wdg_permissions.py
  geoplateforme/gui/permissions/wdg_permissions.ui
Labels: enhancement, UI/UX

#126 feat(permission): add permission creation
  geoplateforme/api/user.py
  geoplateforme/gui/mdl_community.py
  geoplateforme/gui/mdl_offering.py
  geoplateforme/gui/permissions/dlg_permission_creation.py
  geoplateforme/gui/permissions/dlg_permission_creation.ui
  geoplateforme/gui/permissions/wdg_permission_creation.py
  geoplateforme/gui/permissions/wdg_permission_creation.ui
  geoplateforme/gui/permissions/wdg_permissions.py
  geoplateforme/gui/permissions/wdg_permissions.ui
  geoplateforme/gui/proxy_model_offering.py
Labels: enhancement, UI/UX

#125 Feat/new metadata widget
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/metadata.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
  geoplateforme/gui/metadata/metadata_template
  geoplateforme/gui/metadata/wdg_metadata_details.py
  geoplateforme/gui/metadata/wdg_metadata_details.ui
  geoplateforme/gui/permissions/wdg_permissions.py
  geoplateforme/toolbelt/network_manager.py
Labels: enhancement, UI/UX

#128 feat(user key): add accesses creation processing
  docs/usage/processings.md
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/user_key.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/user_key/create_accesses.py
  geoplateforme/resources/help/create_accesses.md
  tests/qgis/processings/user_key/test_accesses_creation.py
Labels: documentation, enhancement, quality

#129 feat(user key): add dialog to create user key
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/user_permission.py
  geoplateforme/gui/user_keys/dlg_user_key_creation.py
  geoplateforme/gui/user_keys/dlg_user_key_creation.ui
  geoplateforme/gui/user_keys/mdl_user_permissions.py
  geoplateforme/gui/user_keys/wdg_user_key_creation.py
  geoplateforme/gui/user_keys/wdg_user_key_creation.ui
  geoplateforme/gui/user_keys/wdg_user_key_ip_filter.py
  geoplateforme/gui/user_keys/wdg_user_key_ip_filter.ui
  geoplateforme/gui/user_keys/wdg_user_keys.py
  geoplateforme/gui/user_keys/wdg_user_keys.ui
Labels: enhancement, UI/UX

#132 feat(user key): display user key
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/key_access.py
  geoplateforme/api/permissions.py
  geoplateforme/gui/user_keys/mdl_user_keys.py
  geoplateforme/gui/user_keys/mdl_user_permissions.py
  geoplateforme/gui/user_keys/wdg_user_key.py
  geoplateforme/gui/user_keys/wdg_user_key.ui
  geoplateforme/gui/user_keys/wdg_user_keys.py
Labels: enhancement, UI/UX

#136 feat(user key): add specific component for IP CIDR adress edit
  geoplateforme/gui/user_keys/wdg_ip_filter_table.py
  geoplateforme/gui/user_keys/wdg_ip_filter_table.ui
  geoplateforme/toolbelt/lne_ip_cidr_adress.py
Labels: enhancement, UI/UX

#140 feat(user key): add processing and GUI for update
  docs/usage/processings.md
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/user_key.py
  geoplateforme/gui/user_keys/mdl_user_permissions.py
  geoplateforme/gui/user_keys/wdg_ip_filter_table.py
  geoplateforme/gui/user_keys/wdg_user_key.py
  geoplateforme/gui/user_keys/wdg_user_key.ui
  geoplateforme/gui/user_keys/wdg_user_key_ip_filter.py
  geoplateforme/gui/user_keys/wdg_user_keys.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/tools/delete_offering.py
  geoplateforme/processing/user_key/update_key.py
  geoplateforme/resources/help/update_key.md
  geoplateforme/toolbelt/network_manager.py
  tests/qgis/processings/user_key/test_key_update.py
Labels: documentation, enhancement, quality, UI/UX

#141 feat(permission): add widget to display / delete / update permission
  docs/usage/processings.md
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/permissions.py
  geoplateforme/gui/dashboard/wdg_service_details.ui
  geoplateforme/gui/mdl_offering.py
  geoplateforme/gui/permissions/mdl_permissions.py
  geoplateforme/gui/permissions/wdg_permission.py
  geoplateforme/gui/permissions/wdg_permission.ui
  geoplateforme/gui/permissions/wdg_permission_creation.py
  geoplateforme/gui/permissions/wdg_permissions.py
  geoplateforme/gui/user_keys/mdl_user_permissions.py
  geoplateforme/processing/permissions/delete_permission.py
  geoplateforme/processing/permissions/update_permission.py
  geoplateforme/processing/provider.py
  geoplateforme/resources/help/delete_permission.md
  geoplateforme/resources/help/update_permission.md
  tests/qgis/processings/permissions/test_permission_delete.py
  tests/qgis/processings/permissions/test_permission_update.py
Labels: documentation, enhancement, quality, UI/UX

#143 feat(permission): display public community for creation
  geoplateforme/api/catalogs.py
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/user.py
  geoplateforme/gui/mdl_community.py
Labels: enhancement, UI/UX

#144 fix(processing): add output to be able to use processing in QGIS modeler
  geoplateforme/processing/generation/create_raster_tiles_from_wms_vector.py
  geoplateforme/processing/generation/tile_creation.py
  geoplateforme/processing/generation/upload_database_integration.py
  geoplateforme/processing/permissions/create_permission.py
  geoplateforme/processing/publication/upload_publication.py
  geoplateforme/processing/publication/wfs_publication.py
  geoplateforme/processing/publication/wms_publication.py
  geoplateforme/processing/publication/wms_raster_publication.py
  geoplateforme/processing/publication/wmts_publication.py
  geoplateforme/processing/tools/check_layer.py
  geoplateforme/processing/tools/create_geoserver_style.py
  geoplateforme/processing/upload/upload_from_files.py
  geoplateforme/processing/upload/upload_from_layers.py
  geoplateforme/processing/user_key/create_basic_key.py
  geoplateforme/processing/user_key/create_hash_key.py
  geoplateforme/processing/user_key/create_oauth_key.py
  geoplateforme/resources/help/check_layers.md
  geoplateforme/resources/help/create_permission.md
  geoplateforme/resources/help/tile_creation.md
  geoplateforme/resources/help/upload_database_integration.md
  tests/qgis/processings/permissions/test_permission_creation.py
Labels: bug, quality

#145 feat(permission): small fixes and add option to delete added user and community
  geoplateforme/gui/permissions/wdg_permission_creation.py
  geoplateforme/gui/permissions/wdg_permission_creation.ui
  geoplateforme/gui/user_keys/proxy_model_user_permissions.py
  geoplateforme/gui/user_keys/wdg_user_key_creation.ui
  geoplateforme/gui/user_keys/wdg_user_keys.py
  geoplateforme/gui/user_keys/wdg_user_keys.ui
  geoplateforme/toolbelt/lne_uuid.py
Labels: enhancement, UI/UX

#148 feat(style): new processing to add style to service configuration
  docs/usage/processings.md
  geoplateforme/api/configuration.py
  geoplateforme/api/custom_exceptions.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/style/add_configuration_style.py
  geoplateforme/resources/help/add_configuration_style.md
  tests/qgis/processings/style/test_add_configuration_style.py
Labels: documentation, enhancement, quality
