Repository Geoplateforme/plugin-qgis-geoplateforme, pull requests merged in 2025-08, with the labels that each got.

#166 feat(metadata): Update metadata links (access, styles and getCapabilities)
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/datastore.py
  geoplateforme/api/metadata.py
  geoplateforme/gui/create_raster_tiles_from_wms_vector/qwp_tile_generation_status.py
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/gui/qwp_metadata_form.py
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
  geoplateforme/gui/wms_raster_publication/qwp_wms_raster_publication_status.py
  geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
  geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
  geoplateforme/processing/publication/upload_publication.py
  geoplateforme/processing/publication/wfs_publication.py
  geoplateforme/processing/publication/wms_publication.py
  geoplateforme/processing/publication/wms_raster_publication.py
  geoplateforme/processing/publication/wmts_publication.py
Labels: UI/UX

#185 fix(search): add tag widget for theme field and fix production year search
  geoplateforme/gui/metadata/wdg_tagbar.py
  geoplateforme/gui/provider/provider_dialog.py
  geoplateforme/gui/provider/provider_dialog.ui
Labels: bug, UI/UX

#187 fix(permission): invalid groupId for create_permission
  geoplateforme/processing/permissions/create_permission.py
Labels: bug

#188 fix(user key): login and password are mandatory for BASIC key
  geoplateforme/gui/user_keys/dlg_user_key_creation.py
  geoplateforme/gui/user_keys/wdg_user_key_creation.py
Labels: bug, UI/UX

#193 fix(stored data): need to check enum not string for status text
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
Labels: bug, UI/UX

#195 fix(actions): use layout instead of toolbar for actions
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/dashboard/dlg_stored_data_details.ui
  geoplateforme/gui/dashboard/wdg_service_details.py
  geoplateforme/gui/dashboard/wdg_service_details.ui
  geoplateforme/gui/dashboard/wdg_upload_details.py
  geoplateforme/gui/dashboard/wdg_upload_details.ui
Labels: bug, UI/UX

#197 fix(stored data): allow delete if status is UNSTABLE
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
Labels: bug, UI/UX

#196 feat(sld): add option to create sld file from layer
  geoplateforme/gui/styles/wdg_sld_selection.py
  geoplateforme/gui/styles/wdg_sld_selection.ui
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
  geoplateforme/gui/wms_vector_publication/wdg_table_style_selection.py
  geoplateforme/gui/wms_vector_publication/wdg_table_style_selection.ui
  geoplateforme/processing/tools/sld11-10.xsl
  geoplateforme/processing/tools/sld_downgrade.py
Labels: enhancement, UI/UX

#198 feat(publish): add page to define publication visibility
  geoplateforme/api/offerings.py
  geoplateforme/gui/publication/qwp_visibility.py
  geoplateforme/gui/publication/qwp_visibility.ui
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/gui/publication_creation/wzd_publication_creation.py
  geoplateforme/gui/qwp_metadata_form.py
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
  geoplateforme/gui/wfs_publication/wzd_publication_creation.py
  geoplateforme/gui/wms_raster_publication/qwp_wms_raster_publication_status.py
  geoplateforme/gui/wms_raster_publication/wzd_publication_creation.py
  geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
  geoplateforme/gui/wms_vector_publication/wzd_publication_creation.py
  geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
  geoplateforme/gui/wmts_publication/wzd_publication_creation.py
  geoplateforme/processing/publication/upload_publication.py
  geoplateforme/processing/publication/wfs_publication.py
  geoplateforme/processing/publication/wms_publication.py
  geoplateforme/processing/publication/wms_raster_publication.py
  geoplateforme/processing/publication/wmts_publication.py
  geoplateforme/resources/help/vector_tile_publish.md
  geoplateforme/resources/help/wfs_publish.md
  geoplateforme/resources/help/wms_publish.md
  geoplateforme/resources/help/wms_raster_publish.md
  geoplateforme/resources/help/wmts_publish.md
Labels: enhancement, UI/UX

#199 fix(provider): use user define authid for authentication
  geoplateforme/gui/provider/capabilities_reader.py
  geoplateforme/gui/provider/provider_dialog.py
Labels: bug, UI/UX

#202 feat(dashboard): add button to delete current dataset
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
Labels: enhancement, UI/UX

#212 feat(offering): allow delete of UNSTABLE offerings
  geoplateforme/gui/dashboard/wdg_service_details.py
Labels: enhancement, UI/UX

#213 feat(wfs): add validator for public name
  geoplateforme/gui/wfs_publication/wdg_table_relation.py
Labels: enhancement, UI/UX

#219 feat(sld from layer): disable checks to avoid error if proxy needed for schema download
  geoplateforme/gui/styles/wdg_sld_selection.py
Labels: bug, enhancement, UI/UX

#237 fix(processing): be more robust for processing search from id
  geoplateforme/toolbelt/preferences.py
Labels: bug

#239 fix(report): avoid duplicate of generation report
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/dashboard/wdg_upload_details.py
Labels: bug, UI/UX
