Repository Geoplateforme/plugin-qgis-geoplateforme, pull requests merged in 2025-05, with the labels that each got.

#31 1- feat(upload): add processing for creation from QGIS layer
  geoplateforme/processing/provider.py
  geoplateforme/processing/upload_from_files.py
  geoplateforme/processing/upload_from_layers.py
  geoplateforme/processing/utils.py
  geoplateforme/resources/help/upload_from_layers.md
Labels: enhancement

#32 feature(dashboard): add button to create a new dataset or add data to existing dataset
  geoplateforme/gui/cbx_dataset.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/gui/upload_creation/qwp_upload_edition.py
  geoplateforme/gui/upload_creation/wdg_upload_creation.py
  geoplateforme/gui/upload_creation/wdg_upload_creation.ui
  geoplateforme/gui/upload_creation/wzd_upload_creation.py
  geoplateforme/plugin_main.py
Labels: enhancement, UI/UX

#35 4- feat(upload to vector): refactor to replace .json by processing parameter
  geoplateforme/processing/upload_database_integration.py
  geoplateforme/processing/vector_db_creation.py
  geoplateforme/resources/help/upload_database_integration.md
Labels: documentation, enhancement

#36 5- feat(upload from layer): add additionnal files option
  docs/usage/processings.md
  geoplateforme/processing/upload_from_layers.py
  geoplateforme/resources/help/upload_from_layers.md
Labels: documentation, enhancement

#37 feat(layer selection): new ui for layer and file selection
  geoplateforme/gui/upload_creation/mdl_upload_files.py
  geoplateforme/gui/upload_creation/wdg_layer_selection.py
  geoplateforme/gui/upload_creation/wdg_layer_selection.ui
  geoplateforme/gui/upload_creation/wdg_upload_creation.py
  geoplateforme/gui/upload_creation/wdg_upload_creation.ui
  geoplateforme/processing/upload_from_layers.py
Labels: enhancement, UI/UX

#38 feat(vector db creation): use layers for vector db creation
  docs/usage/processings.md
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/processing/upload_database_integration.py
  geoplateforme/processing/upload_from_layers.py
  geoplateforme/processing/vector_db_creation.py
  geoplateforme/resources/help/vector_db_creation.md
Labels: documentation, enhancement, UI/UX

#39 feat(tile generation): add action for tile generation in vector db stored data details
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/mdl_stored_data.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py
  geoplateforme/gui/tile_creation/wzd_tile_creation.py
Labels: enhancement, UI/UX

#40 feat(tile publish): add action for tile publication in pyramid vector stored data details
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/publication_creation/qwp_publication_form.py
  geoplateforme/gui/publication_creation/wzd_publication_creation.py
Labels: enhancement, UI/UX

#41 feat(tile generation): refactor to remove JSON file use
  docs/usage/processings.md
  geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
  geoplateforme/processing/tile_creation.py
  geoplateforme/resources/help/tile_creation.md
Labels: documentation, enhancement, UI/UX

#42 feat(tile publish): refactor to remove JSON file use
  docs/usage/processings.md
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/processing/upload_publication.py
  geoplateforme/resources/help/vector_tile_publish.md
Labels: documentation, enhancement, UI/UX

#43 feat(ui): remove action for tile generation and publication from toolbar
  geoplateforme/plugin_main.py
Labels: enhancement

#48 add metadata class and fill by parsing xml
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/metadata.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
Labels: enhancement, UI/UX

#47 feat(dataset): sort by name in combobox
  geoplateforme/gui/cbx_dataset.py
Labels: enhancement, UI/UX

#44 feat(service): display available service in table
  geoplateforme/api/configuration.py
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/stored_data.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
  geoplateforme/gui/mdl_configuration.py
  geoplateforme/gui/publication_creation/wdg_publication_form.py
  geoplateforme/processing/delete_data.py
  geoplateforme/processing/unpublish.py
  geoplateforme/processing/upload_publication.py
Labels: enhancement, UI/UX

#45 feat(upload): add widget to display upload details
  geoplateforme/api/upload.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_upload_details.py
  geoplateforme/gui/dashboard/wdg_upload_details.ui
Labels: enhancement, UI/UX

#46 feat(external plugins): add dependencies and load actions in Geoplateforme plugin
  geoplateforme/constants.py
  geoplateforme/metadata.txt
  geoplateforme/plugin_main.py
Labels: enhancement

#50 feat(processing): add available processings name in settings (not visible to user)
  geoplateforme/api/processing.py
  geoplateforme/processing/tile_creation.py
  geoplateforme/processing/upload_database_integration.py
  geoplateforme/toolbelt/preferences.py
Labels: enhancement

#51 feat(upload): check if db integration has started before wizard close
  geoplateforme/gui/upload_creation/wzd_upload_creation.py
Labels: enhancement, UI/UX

#52 feat(auth): add user dialog if log in
  geoplateforme/gui/dlg_authentication.py
  geoplateforme/gui/dlg_authentication.ui
  geoplateforme/gui/user/dlg_user.py
  geoplateforme/plugin_main.py
Labels: enhancement, UI/UX

#53 release: bump version to 0.4.0
  .github/workflows/linter.yml
  .github/workflows/tester.yml
  CHANGELOG.md
  geoplateforme/metadata.txt
Labels: ci-cd

#58 fix(metadata): use temporary file name only but not with context
  geoplateforme/api/metadata.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/toolbelt/network_manager.py
Labels: bug, UI/UX

#71 fix(network manager): don't push log in message bar to avoid crashes in Windows
  geoplateforme/toolbelt/network_manager.py
Labels: bug

#72 fix(upload): set datasetname in tags
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
Labels: bug, UI/UX

#74 Fix/no crs if no layer from qgis
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/processing/upload_from_layers.py
  geoplateforme/processing/vector_db_creation.py
  geoplateforme/resources/help/upload_from_layers.md
  geoplateforme/resources/help/vector_db_creation.md
Labels: bug, UI/UX

#62 Feat/minimal sld downgrade
  docs/usage/processings.md
  geoplateforme/processing/provider.py
  geoplateforme/processing/sld11-10.xsl
  geoplateforme/processing/sld_downgrade.py
  geoplateforme/resources/help/sld_downgrade.md
Labels: documentation, enhancement

#75 fix(upload): always use temporary file for gpkg layers to avoid upload of other layers
  geoplateforme/processing/upload_from_layers.py
Labels: bug

#79 feat(vector db): add generation wizard
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_upload_details.py
  geoplateforme/gui/upload_database_integration/qwp_upload_database_integration.py
  geoplateforme/gui/upload_database_integration/qwp_upload_database_integration.ui
  geoplateforme/gui/upload_database_integration/qwp_vector_db_edition.py
  geoplateforme/gui/upload_database_integration/qwp_vector_db_edition.ui
  geoplateforme/gui/upload_database_integration/wzd_upload_database_integration.py
Labels: enhancement, UI/UX

#81 feat(tile): wait option in tile generation processing
  geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
  geoplateforme/processing/tile_creation.py
  geoplateforme/resources/help/tile_creation.md
Labels: enhancement, UI/UX

#88 feat(ui): move to plugin menu and add report button
  geoplateforme/gui/dlg_settings.py
  geoplateforme/plugin_main.py
Labels: enhancement, UI/UX

#85 feat(service): display offering instead of configuration
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/offerings.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/mdl_offering.py
Labels: enhancement, UI/UX

#86 feat(service): add details zone
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
  geoplateforme/gui/dashboard/wdg_service_details.py
  geoplateforme/gui/dashboard/wdg_service_details.ui
Labels: enhancement, UI/UX

#89 fix(upload): add_file need a Path and not a str
  geoplateforme/api/upload.py
  geoplateforme/processing/upload_from_files.py
Labels: bug

#91 fix(tms): need to use ConfigurationType instead of str
  geoplateforme/gui/wdg_publication_form.py
  geoplateforme/processing/upload_publication.py
Labels: bug, UI/UX

#92 feat(publication): select offering after publication
  geoplateforme/api/configuration.py
  geoplateforme/api/offerings.py
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
  geoplateforme/gui/mdl_offering.py
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/gui/publication_creation/qwp_status.ui
  geoplateforme/gui/publication_creation/wzd_publication_creation.py
  geoplateforme/gui/update_publication/wzd_update_publication.py
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.ui
  geoplateforme/gui/wfs_publication/wzd_publication_creation.py
  geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
  geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.ui
  geoplateforme/gui/wms_vector_publication/wzd_publication_creation.py
  geoplateforme/processing/upload_publication.py
  geoplateforme/processing/wfs_publication.py
  geoplateforme/processing/wms_publication.py
  geoplateforme/resources/help/vector_tile_publish.md
Labels: enhancement, UI/UX

#95 fix(endpoint): add option to use open endpoint
  geoplateforme/api/datastore.py
Labels: bug
