Repository Geoplateforme/plugin-qgis-geoplateforme, pull requests merged in 2025-04, with the labels that each got.

#4 fix(quality): apply Qt6 migration script
  geoplateforme/api/client.py
  geoplateforme/api/user.py
  geoplateforme/gui/dlg_settings.py
  geoplateforme/plugin_main.py
Labels: bug, quality

#2 Add OAuth2 authentication
  geoplateforme/api/configuration.py
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/datastore.py
  geoplateforme/api/processing.py
  geoplateforme/api/stored_data.py
  geoplateforme/api/upload.py
  geoplateforme/api/user.py
  geoplateforme/api/utils.py
  geoplateforme/auth/oauth2_config.json
  geoplateforme/constants.py
  geoplateforme/datamodels/__init__.py
  geoplateforme/datamodels/oauth2_configuration.py
  geoplateforme/gui/dlg_authentication.py
  geoplateforme/gui/dlg_authentication.ui
  geoplateforme/plugin_main.py
  geoplateforme/processing/check_layer.py
  geoplateforme/toolbelt/file_stats.py
  geoplateforme/toolbelt/network_manager.py
  geoplateforme/toolbelt/preferences.py
  scripts/generate_translation_profile.py
  tests/qgis/test_plg_preferences.py
Labels: quality, UI/UX

#5 update(tooling): set ruff as Python formatter in VS Code
  .vscode/settings.json
Labels: tooling

#6 Nettoyage et refactoring du Network Manager
  geoplateforme/api/check.py
  geoplateforme/api/client.py
  geoplateforme/api/upload.py
  geoplateforme/gui/dlg_authentication.py
  geoplateforme/gui/dlg_settings.py
  geoplateforme/gui/dlg_settings.ui
  geoplateforme/processing/upload_creation.py
  geoplateforme/toolbelt/__init__.py
  geoplateforme/toolbelt/network_manager.py
  geoplateforme/toolbelt/preferences.py
  tests/dev/dev_auth_flow_requests.py
  tests/qgis/test_plg_preferences.py
Labels: quality, UI/UX

#9 refactor(stored data): optimize stored data for better load
  geoplateforme/api/stored_data.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/mdl_dataset.py
  geoplateforme/gui/mdl_stored_data.py
  geoplateforme/gui/proxy_model_stored_data.py
  geoplateforme/gui/report/dlg_report.py
  geoplateforme/gui/storage/dlg_storage_report.py
  geoplateforme/processing/tile_creation.py
  geoplateforme/toolbelt/network_manager.py
Labels: UI/UX

#11 CI: fix packaged plugin and repository was missing in documentation
  .github/workflows/documentation.yml
  .github/workflows/linter.yml
  .github/workflows/package_and_release.yml
  .github/workflows/tester.yml
  geoplateforme/metadata.txt
Labels: bug, ci-cd

#12 fix(init): plg_settings.qgis_auth_id can be None and so have no length
  geoplateforme/plugin_main.py
Labels: bug

#13 fix(auth): make QGIS auth configuration map JSON compliant before loading it as JSON
  geoplateforme/api/custom_exceptions.py
  geoplateforme/datamodels/oauth2_configuration.py
  geoplateforme/gui/dlg_authentication.py
Labels: bug, UI/UX

#14 feature(packaging): include oAuth credentials from GH Actions secrets during packaging steps
  .github/workflows/package_and_release.yml
  geoplateforme/auth/oauth2_config.json
Labels: ci-cd, packaging

#16 feature(vector db): restore vector db creation wizard
  geoplateforme/api/processing.py
  geoplateforme/api/stored_data.py
  geoplateforme/api/upload.py
  geoplateforme/gui/report/dlg_report.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
  geoplateforme/gui/update_tile_upload/qwp_update_tile_upload_run.py
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/plugin_main.py
  geoplateforme/processing/tile_creation.py
  geoplateforme/processing/update_tile_upload.py
  geoplateforme/processing/upload_creation.py
  geoplateforme/processing/upload_database_integration.py
  geoplateforme/processing/upload_publication.py
  geoplateforme/processing/vector_db_creation.py
  geoplateforme/toolbelt/network_manager.py
Labels: enhancement, UI/UX

#18 fix(user): fix community without user
  geoplateforme/api/user.py
Labels: bug

#22 fix(plugin): Qt6 flag is supportsQt6 not qt6_compatible
  geoplateforme/metadata.txt
Labels: bug, packaging

#20 feature(vector tile publish): restore publication wizard
  geoplateforme/api/configuration.py
  geoplateforme/api/datastore.py
  geoplateforme/gui/publication_creation/qwp_publication_form.py
  geoplateforme/gui/publication_creation/qwp_publication_form.ui
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/plugin_main.py
  geoplateforme/processing/upload_publication.py
Labels: enhancement, UI/UX

#21 feat(network manager): get error from request reply
  geoplateforme/toolbelt/network_manager.py
Labels: enhancement

#23 feature(upload) : refactor upload creation
  docs/index.md
  docs/usage/processings.md
  geoplateforme/gui/update_tile_upload/qwp_update_tile_upload_run.py
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/upload_creation.py
  geoplateforme/processing/upload_from_files.py
  geoplateforme/processing/utils.py
  geoplateforme/processing/vector_db_creation.py
  geoplateforme/resources/help/upload_from_files.md
Labels: documentation, enhancement, UI/UX

#24 release: bump version to 0.2.0-beta2
  CHANGELOG.md
Labels: documentation

#27 update(ui): use logo proposed by @IGNF-Xavier
  geoplateforme/resources/images/logo.svg
Labels: UI/UX

#25 fix(datastore selection): disable signal connection during update
  geoplateforme/gui/publication_creation/qwp_publication_form.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py
  geoplateforme/gui/update_publication/qwp_update_publication_form.py
  geoplateforme/gui/update_tile_upload/qwp_update_tile_upload_edition.py
Labels: bug, UI/UX

#26 feat(tile creation): no upload remove after creation
  geoplateforme/processing/tile_creation.py
Labels: enhancement

#28 fix(tile publish): invalid levels used
  geoplateforme/gui/publication_creation/qwp_status.py
Labels: bug, UI/UX

#29 release: bump version to 0.3.0-beta1
  CHANGELOG.md
  geoplateforme/metadata.txt
Labels: documentation
