Repository Geoplateforme/plugin-qgis-geoplateforme, pull requests merged in 2025-10, with the labels that each got.

#362 fix(provider): display subset editor only when WFS layer is valid
  geoplateforme/gui/provider/provider_dialog.py
Labels: bug, UI/UX

#381 fix(tile_generation): fix regression for select zoom level
  geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
Labels: bug, UI/UX

#383 fix(dashboard): add button to delete open upload
  geoplateforme/gui/dashboard/wdg_upload_details.py
Labels: bug, UI/UX

#368 Update integration.md
  docs/external_plugins/integration.md
Labels: documentation

#363 fix(metadata): fix regex for metadata unique id
  geoplateforme/gui/qwp_metadata_form.py
Labels: bug, UI/UX

#389 feat(optim): avoid data load for publication
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/publication_creation/qwp_publication_form.py
  geoplateforme/gui/publication_creation/qwp_publication_form.ui
  geoplateforme/gui/publication_creation/wzd_publication_creation.py
  geoplateforme/gui/wfs_publication/qwp_table_relation.py
  geoplateforme/gui/wfs_publication/qwp_table_relation.ui
  geoplateforme/gui/wfs_publication/wzd_publication_creation.py
  geoplateforme/gui/wms_vector_publication/qwp_table_style_selection.py
  geoplateforme/gui/wms_vector_publication/qwp_table_style_selection.ui
  geoplateforme/gui/wms_vector_publication/wzd_publication_creation.py
Labels: enhancement, UI/UX

#391 Feat/no freeze for check layer
  geoplateforme/gui/upload_creation/wdg_upload_creation.py
  geoplateforme/processing/tools/check_layer.py
  tests/qgis/processings/test_check_layer.py
Labels: enhancement, quality, UI/UX

#392 fix(TMS): fix regex for valid table
  geoplateforme/gui/mdl_table_relation.py
Labels: bug, UI/UX
