Repository Geoplateforme/plugin-qgis-geoplateforme, pull requests merged in 2025-09, with the labels that each got.

#247 fix(doc): invalid links for processings
  docs/usage/processings.md
  geoplateforme/processing/utils.py
Labels: bug, documentation

#250 Fix/update user key accesses
  docs/usage/processings.md
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/key_access.py
  geoplateforme/gui/user_keys/wdg_user_key.py
  geoplateforme/processing/provider.py
  geoplateforme/processing/user_key/delete_user_key_accesses.py
  geoplateforme/resources/help/delete_user_key_accesses.md
Labels: bug, documentation, UI/UX

#253 feat(wfs): use QScrollArea to use collapsible group box
  geoplateforme/gui/wfs_publication/qwp_table_relation.ui
Labels: bug, UI/UX

#254 feat(metadata): edit metadata description with markdown
  geoplateforme/gui/metadata/wdg_metadata_details.ui
  geoplateforme/gui/wdg_publication_form.ui
Labels: enhancement, UI/UX

#255 feat(publish): enable back button in case of publish error
  geoplateforme/gui/publication/qwp_abstract_publish_service.py
  geoplateforme/gui/publication/qwp_visibility.py
  geoplateforme/gui/publication_creation/qwp_status.py
  geoplateforme/gui/wfs_publication/qwp_wfs_publication_status.py
  geoplateforme/gui/wms_raster_publication/qwp_wms_raster_publication_status.py
  geoplateforme/gui/wms_vector_publication/qwp_wms_vector_publication_status.py
  geoplateforme/gui/wmts_publication/qwp_wmts_publication_status.py
Labels: enhancement, UI/UX

#260 Doc/init doc for widget
  docs/external_plugins/integration.md
  docs/index.md
  docs/static/images/advanced_search.png
  docs/static/images/authentication_widget.png
  docs/static/images/cartes_gouv_connection.png
  docs/static/images/connect_button.png
  docs/static/images/create_dataset_widget.png
  docs/static/images/dashboard_button.png
  docs/static/images/dashboard_widget.png
  docs/static/images/data_provider_widget.png
  docs/static/images/data_tab.png
  docs/static/images/key_auth_creation.png
  docs/static/images/key_button.png
  docs/static/images/key_creation.png
  docs/static/images/key_user_exists.png
  docs/static/images/key_widget.png
  docs/static/images/metadata_widget.png
  docs/static/images/permission_creation_widget.png
  docs/static/images/permissions_panel.png
  docs/static/images/permissions_tab.png
  docs/static/images/permissions_widget.png
  docs/static/images/plugin_menu.png
  docs/static/images/plugin_settings.png
  docs/static/images/plugin_toolbar.png
  docs/static/images/plugin_toolbar_disconnected.png
  docs/static/images/private_service_load.png
  docs/static/images/publish_metadata.png
  docs/static/images/publish_page.png
  docs/static/images/publish_restriction.png
  docs/static/images/publish_service_description.png
  docs/static/images/publish_wait_metadata.png
  docs/static/images/publish_wfs_table_selection.png
  docs/static/images/publish_wms_vector_table_selection.png
  docs/static/images/pyr_raster_widget.png
  docs/static/images/pyr_vector_widget.png
  docs/static/images/services_create_style_mapbox.png
  docs/static/images/services_create_style_sld.png
  docs/static/images/services_styles_widget.png
  docs/static/images/services_widget.png
  docs/static/images/upload_checks.png
  docs/static/images/upload_layer_crs_mismatch.png
  docs/static/images/upload_layer_list.png
  docs/static/images/upload_layer_selection.png
  docs/static/images/upload_wait_check.png
  docs/static/images/upload_wait_for_data.png
  docs/static/images/upload_widget.png
  docs/static/images/user_widget.png
  docs/static/images/vector_db_widget.png
  docs/static/images/vector_tiles_generation.png
  docs/static/images/vector_tiles_init_page.png
  docs/static/images/vector_tiles_tables.png
  docs/static/images/vector_tiles_tippecanoe.png
  docs/usage/how_to_use.md
  geoplateforme/gui/dashboard/wdg_service_details.ui
Labels: documentation, UI/UX

#261 fix(offering model): use /datastore/{datastore]/offerings to get list of offering if no dataset defined
  geoplateforme/api/metadata.py
  geoplateforme/api/offerings.py
  geoplateforme/gui/mdl_offering.py
  geoplateforme/gui/permissions/wdg_permission.py
  geoplateforme/gui/permissions/wdg_permission_creation.py
Labels: bug, UI/UX

#286 fix(dashboard): Insensitive sort for dataset
  geoplateforme/gui/cbx_dataset.py
Labels: bug, UI/UX

#287 Feat/add option to define multigeom layers
  geoplateforme/gui/upload_creation/qwp_upload_creation.py
  geoplateforme/gui/upload_creation/wdg_upload_creation.py
  geoplateforme/gui/upload_creation/wdg_upload_creation.ui
  geoplateforme/gui/upload_database_integration/qwp_upload_database_integration.py
  geoplateforme/gui/upload_database_integration/qwp_vector_db_edition.py
  geoplateforme/gui/upload_database_integration/qwp_vector_db_edition.ui
  geoplateforme/processing/generation/upload_database_integration.py
  geoplateforme/resources/help/upload_database_integration.md
Labels: enhancement, UI/UX

#288 fix(metadata): fix metadata url generation and display
  geoplateforme/api/metadata.py
  geoplateforme/gui/metadata/wdg_metadata_details.py
Labels: bug, UI/UX

#292 feat(menu): add separator before external plugin actions
  geoplateforme/plugin_main.py
Labels: enhancement, UI/UX

#300 fix(docs): hyperlink to issue form to submit a third-party plugin was wrong
  docs/external_plugins/integration.md
Labels: bug, documentation

#301 fix(docs): typo in 3rd party criterias
  docs/external_plugins/integration.md
Labels: documentation

#304 Fix/no UI freeze during unpublish
  geoplateforme/api/metadata.py
  geoplateforme/gui/dashboard/wdg_service_details.py
  geoplateforme/toolbelt/dlg_processing_run.py
  geoplateforme/toolbelt/dlg_processing_run.ui
  geoplateforme/toolbelt/text_edit_feedback.py
Labels: bug, UI/UX

#305 fix/(metadata): add /1.0.0 to TMS url
  geoplateforme/api/metadata.py
Labels: bug

#309 fix(dashboard): fix column size in dashboard tables
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/permissions/wdg_permissions.py
Labels: bug, UI/UX

#339 feat(document): display documents in dashboard and add logic for metadata
  geoplateforme/api/annexes.py
  geoplateforme/api/custom_exceptions.py
  geoplateforme/api/metadata.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/gui/dashboard/wdg_dashboard.ui
  geoplateforme/gui/mdl_document.py
  geoplateforme/gui/metadata/wdg_metadata_details.py
Labels: enhancement, UI/UX

#341 Feat/add zoom selection for table
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_edition.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_edition.ui
  geoplateforme/gui/tile_creation/qwp_tile_generation_fields_selection.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_status.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_zoom_selection.py
  geoplateforme/gui/tile_creation/qwp_tile_generation_zoom_selection.ui
  geoplateforme/gui/tile_creation/wdg_zoom_levels_selection.py
  geoplateforme/gui/tile_creation/wdg_zoom_levels_selection.ui
  geoplateforme/gui/tile_creation/wzd_tile_creation.py
Labels: enhancement, UI/UX

#343 feat(user): close dashboard after disconnection or settings reset
  geoplateforme/plugin_main.py
Labels: bug, enhancement

#347 fix(tms): fix reading zoom level in capabilities
  geoplateforme/gui/provider/capabilities_reader.py
Labels: bug, UI/UX

#352 feat(style): avoid freeze for style creation by using processing dialog
  geoplateforme/gui/styles/dlg_configuration_style_creation.py
  geoplateforme/gui/styles/wdg_sld_selection.py
Labels: enhancement, UI/UX

#350 Feat/no UI freeze for dataset delete
  geoplateforme/gui/dashboard/dlg_stored_data_details.py
  geoplateforme/gui/dashboard/wdg_dashboard.py
  geoplateforme/processing/tools/delete_offering.py
  geoplateforme/processing/tools/delete_stored_data.py
  geoplateforme/resources/help/delete_offering.md
Labels: enhancement, UI/UX
